### ISSUE TITLE
Java-Chassis 文档有两处错误

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-docs#254]
1. 负载均衡, [实例隔离的`continuousFailureThreshold`默认值](https://github.com/apache/servicecomb-docs/blob/770246dd21b16d18ff938afff547ec1227204aa4/java-chassis-reference/zh_CN/docs/references-handlers/loadbalance.md?plain=1#L80)应该是`5`, 文档写成了`2`

2. 处理链介绍, [cse.handler.xml配置文件介绍](https://github.com/apache/servicecomb-docs/blob/770246dd21b16d18ff938afff547ec1227204aa4/java-chassis-reference/zh_CN/docs/references-handlers/intruduction.md?plain=1#L63)位置, 原文写的是"增加*.handler.xml文件", 但是 Java-Chassis 源码中加载代码如下:
    ```java
        List<Resource> resList =
        PaaSResourceUtils.getSortedResources("classpath*:config/cse.handler.xml", ".handler.xml");
    ```
    业务反馈只有 cse.handler.xml 文件才能生效, 其他的 *.handler.xml 文件名是不行的. 建议文档明确写成 "cse.handler.xml", 并说明必须放在`classpath*:config/`路径下.

**Comment by lbc97** [comment]
https://github.com/apache/servicecomb-docs/pull/255 ，this bug will be fixed in the next update.
