### ISSUE TITLE
2.x url is invalid

### ISSUE THREAD

**Issue by chendongcse** [apache/servicecomb-docs#288]
In this[ page](https://huaweicse.github.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/)

<html>
<body>

2.8.x | [中文](https://servicecomb.apache.org/references/java-chassis/2.x/zh_CN/), [English](https://servicecomb.apache.org/references/java-chassis/2.x/en_US/)
-- | --

</body>
</html>
url in the box is invaild

**Comment by liubao68** [comment]
This page is in developing and not released. We are working on this.
